### ISSUE TITLE
The `payload.record` object appears to have a deserialized/transformed timestamp?

### ISSUE THREAD

**Issue by acupofjose** [supabase/realtime#114]
# Bug report

## Describe the bug

I'm attempting to deserialize the timestamp on a record that has been inserted. However, it seems that `realtime` does some deserialization/transformation on the record before returning it as an event.

While it may seem a trivial bug, it affects the way in which parsing of timestamps happens from the application level.

## To Reproduce

**Postgresql Setup** 
```sql
CREATE TABLE public.todos (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  details text,
  user_id bigint REFERENCES users NOT NULL,
  inserted_at timestamp without time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO 
    public.todos (details, user_id)
VALUES 
    ('Star the repo', 1),
    ('Watch the releases', 2);
```
A JSON response from postgrest returns:
```json
{
  "id": 1,
  "details": "Star the repo",
  "user_id": 1,
  "inserted_at": "2021-02-06T13:51:13.827371"
},
{
  "id": 2,
  "details": "Watch the releases",
  "user_id": 2,
  "inserted_at": "2021-02-06T13:51:13.827371"
}
```

Inserting a new record while subscribed to realtime returns:
```json
{
  "event": "*",
  "payload": {
    "columns": [
      {
        "flags": [
          "key"
        ],
        "name": "id",
        "type": "int8",
        "type_modifier": 4294967295
      },
      {
        "flags": [],
        "name": "details",
        "type": "text",
        "type_modifier": 4294967295
      },
      {
        "flags": [],
        "name": "user_id",
        "type": "int8",
        "type_modifier": 4294967295
      },
      {
        "flags": [],
        "name": "inserted_at",
        "type": "timestamp",
        "type_modifier": 4294967295
      }
    ],
    "commit_timestamp": "2021-02-06T14:44:57Z",
    "record": {
      "details": "I'm a new todo!",
      "id": "3",
      "inserted_at": "2021-02-06 14:44:57.875382",
      "user_id": "1"
    },
    "schema": "public",
    "table": "todos",
    "type": "INSERT"
  },
  "ref": null,
  "topic": "realtime:public:todos"
}
```

## Expected behavior

Expected output is for the timestamp on `payload.record.inserted_at` to return the raw postgrest timestamp, not a modified form of it.

Expected: `2021-02-06T14:44:57.875382`
Received: `2021-02-06 14:44:57.875382`

## System information

- OS: macOS, docker

`docker-compose.yml`
```yml
version: "2.3"

services:
  rest:
    image: postgrest/postgrest:v7.0.1
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_SCHEMA: public, personal
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      - db

  realtime:
    image: supabase/realtime:latest
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      PORT: 4000
      HOSTNAME: localhost
      JWT_SECRET: SOMETHING_SUPER_SECRET
      SECURE_CHANNELS: "false"
    depends_on:
      - db
  db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./RealtimeTests/db:/docker-entrypoint-initdb.d/
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_PASSWORD: postgres
```
