### ISSUE TITLE
econnrefused error when trying to connect to database

### ISSUE THREAD

**Issue by omidh28** [supabase/realtime#173]
# Bug report

## Describe the bug

Unable to connect to pg database using latest image.

Error:

```
realtime_1  | 2021-08-16 12:52:54.932 [error] GenServer Realtime.Adapters.Postgres.EpgsqlServer terminating
realtime_1  | ** (stop) false
realtime_1  | Last message: {:continue, :db_connect}
realtime_1  | 2021-08-16 12:52:54.932 [error] GenServer #PID<0.3140.0> terminating
realtime_1  | ** (stop) :econnrefused
realtime_1  | Last message (from Realtime.Adapters.Postgres.EpgsqlServer): {:command, :epgsql_cmd_connect, %{database: "postgres", host: 'db', password: #Function<0.109015737/0 in :epgsql_cmd_connect.hide_password/1>, port: 5433, ssl: true, username: "postgres"}}
```

## To Reproduce

Use this compose file or the readme instruction in current repository.

```
version: "3"
services:
  realtime:
    image: supabase/realtime:latest
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      PORT: 4000
      HOSTNAME: localhost
      JWT_SECRET: SOMETHING_SUPER_SECRET
      SECURE_CHANNELS: "true"
    depends_on:
      - db
  db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_PASSWORD: postgres
```
## Expected behavior

It is expected to be connected to db without any issue.

## System information

- OS: Tried on both Windows and Ubuntu.
- Postgresql: 12, 13

## Additional context

I'm trying to use realtime standalone not along with any other supabase projects.
