### ISSUE TITLE
Not works with Amazon Aurora

### ISSUE THREAD

**Issue by mats16** [supabase/realtime#270]
# Bug report

## Describe the bug

The supabase-realtime server does not work with Amazon Aurora PostgreSQL.

## To Reproduce

1. Change parameters for replications
```
      parameters: {
        'rds.logical_replication': '1',
        'max_replication_slots': '5',
        'max_wal_senders': '10',
        'max_logical_replication_workers': '2',
        'max_slot_wal_keep_size': '1024',
      },
```

2. Create PostgreSQL Cluster (v14.3)

3. Launch supabase-realtime server and connect DB

4. The following log is displayed
```
2022-08-02 00:41:28.315 [info] Running RealtimeWeb.Endpoint with cowboy 2.8.0 at :::4000 (http)

2022-08-02 00:41:28.316 [info] Access RealtimeWeb.Endpoint at http://localhost:4000

2022-08-02 00:42:28.341 [error] %RuntimeError{message: "operation :rollback is manually rolling back, which is not supported by Ecto.Multi"}

2022-08-02 00:42:28.377 [error] %Postgrex.Error{connection_id: 16419, message: nil, postgres: %{code: :undefined_object, file: "slot.c", line: "418", message: "replication slot \"realtime_rls\" does not exist", pg_code: "42704", routine: "ReplicationSlotAcquire", severity: "ERROR", unknown: "ERROR"}, query: nil}
```

## Expected behavior

It works well, because it does not rely on extensions.

## Screenshots

N/A

## System information

- Version of supabase-realtime: v0.22.7
- Version of PostgreSQL: 14.3

**Comment by w3b6x9** [comment]
@mats16 did you make sure you have everything configured according to instructions found here:  https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Replication.Logical.html#AuroraPostgreSQL.Replication.Logical.Configure

**Comment by mats16** [comment]
Thanks! I already checked it...

I would like to  create supabase_admin as rds_superuser in rds and try...

**Comment by w3b6x9** [comment]
@mats16 can you please share your config, if possible?

**Comment by mats16** [comment]
Thanks.
This is my settings.

ParameterGroup (for Amazon Aurora PostgreSQL 14): 
```ts
    const parameterGroup = new rds.ParameterGroup(scope, 'ParameterGroup', {
      engine: rds.DatabaseClusterEngine.auroraPostgres({ version: rds.AuroraPostgresEngineVersion.of('14.3', '14') }),
      parameters: {
        'rds.logical_replication': '1',
        'max_replication_slots': '5', // Default Aurora:20, Supabase:5
        'max_wal_senders': '10', // Default Aurora:20, Supabase:10
        'max_logical_replication_workers': '2',
        'autovacuum_max_workers': 'GREATEST({DBInstanceClassMemory/64371566592},2)', // Default: GREATEST({DBInstanceClassMemory/64371566592},3)
        'max_parallel_workers': '4', // Default: GREATEST(${DBInstanceVCPU/2},8)

        'max_slot_wal_keep_size': '1024', // https://github.com/supabase/realtime
      },
    });
```

Realtime server config as docker-compose.yml: 
```yaml
version: '3'
services:
  realtime:
    image: supabase/realtime:v0.22.7
    ports:
      - 4000:4000
    environment:
      DB_HOST: "xxxxx.cluster-xxxxx.us-west-2.rds.amazonaws.com"
      DB_NAME: postgres
      DB_USER: supabase_admin # it is rds_superuser
      DB_PASSWORD: "xxxx"
      DB_PORT: 5432
      DB_SSL: "false"
      PORT: 4000
      JWT_SECRET: "xxx"
      REPLICATION_MODE: RLS
      REPLICATION_POLL_INTERVAL: 100
      SECURE_CHANNELS: "false"
      SLOT_NAME: realtime_rls
      TEMPORARY_SLOT: "true"
      MAX_REPLICATION_LAG_MB: 1000
    command: >
      bash -c "./prod/rel/realtime/bin/realtime eval Realtime.Release.migrate
      && ./prod/rel/realtime/bin/realtime start"
```

Test CDK project: https://github.com/mats16/supabase-on-aws
