### ISSUE TITLE
The browser can't connect to the realtime server (docker, self-hosted)

### ISSUE THREAD

**Issue by felixwochnick** [supabase/realtime#561]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The browser can't connect to the realtime server.

## To Reproduce

```yml
# docker-compose.yml

#...

  realtime:
    container_name: vs-supabase-realtime
    image: supabase/realtime:v2.9.2
    depends_on:
      db:
        # Disable this if you are using an external Postgres database
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "printf \\0 > /dev/tcp/localhost/4000"
        ]
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: supabase_admin
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_AFTER_CONNECT_QUERY: 'SET search_path TO _realtime'
      DB_ENC_KEY: supabaserealtime
      API_JWT_SECRET: ${JWT_SECRET}
      FLY_ALLOC_ID: fly123
      FLY_APP_NAME: realtime
      SECRET_KEY_BASE: 'UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq'
      ERL_AFLAGS: -proto_dist inet_tcp
      ENABLE_TAILSCALE: "false"
      DNS_NODES: "''"
    command: >
      sh -c "/app/bin/migrate && /app/bin/realtime eval 'Realtime.Release.seeds(Realtime.Repo)' && /app/bin/server"
# ...
```

```yml
# kong.yml

#...

## Secure Realtime routes
  - name: realtime-v1
    _comment: "Realtime: /realtime/v1/* -> ws://realtime:4000/socket/*"
    url: http://realtime:4000/socket/
    routes:
      - name: realtime-v1-all
        strip_path: true
        paths:
          - /realtime/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false

#...
```

## Screenshots

realtime container logs:
![image](https://user-images.githubusercontent.com/59612999/226983669-3d28b260-063d-434e-804d-97d7154951f0.png)

kong container logs:
![image](https://user-images.githubusercontent.com/59612999/226984174-62aced17-d1b8-4b9d-928b-ec591c43ee69.png)

firefox:
![image](https://user-images.githubusercontent.com/59612999/226985404-67a8b0ca-a8e4-4c36-b820-675023ea2f59.png)

## System information

- OS: Docker (self hosted)
- Browser: all
