### ISSUE TITLE
Docker-compose file appears to be broken

### ISSUE THREAD

**Issue by ventsyv** [supabase/realtime#658]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I commented out the build instruction and changed the image to be use to v 2.22.5 (latest version available on DockerHub at this time) in the docker-compose file and tried starting realtime up but it wouldn't start

## To Reproduce
Run `docker-compose -f docker-compose_rt.yml up` where the docker compose file is:

```
version: '3'

services:
  db:
    image: supabase/postgres:14.1.0.105
    container_name: realtime-db
    ports:
      - "5432:5432"
    volumes:
      - ./dev/postgres:/docker-entrypoint-initdb.d/
    command: postgres -c config_file=/etc/postgresql/postgresql.conf 
    environment:
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_PASSWORD: postgres

  realtime:
    depends_on:
      - db
    #build: .
    image: supabase/realtime:v2.22.5
    container_name: realtime-server
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_ENC_KEY: supabaserealtime
      DB_AFTER_CONNECT_QUERY: 'SET search_path TO _realtime'
      API_JWT_SECRET: dc447559-996d-4761-a306-f47a5eab1623
      FLY_ALLOC_ID: fly123
      FLY_APP_NAME: realtime
      SECRET_KEY_BASE: UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq
      ERL_AFLAGS: -proto_dist inet_tcp
      ENABLE_TAILSCALE: "false"
      DNS_NODES: "''"
    command: sh -c "/app/bin/migrate && /app/bin/realtime eval 'Realtime.Release.seeds(Realtime.Repo)' && /app/bin/server"


```
and I get the following output:

```
Starting realtime-db ... done
Recreating realtime-server ... done
Attaching to realtime-db, realtime-server
realtime-db | 
realtime-db | PostgreSQL Database directory appears to contain a database; Skipping initialization
realtime-db | 
realtime-db |  2023-09-05 16:38:00.017 UTC [1] LOG:  pgaudit extension initialized
realtime-db |  2023-09-05 16:38:00.062 UTC [1] LOG:  starting PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
realtime-db |  2023-09-05 16:38:00.062 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
realtime-db |  2023-09-05 16:38:00.062 UTC [1] LOG:  listening on IPv6 address "::", port 5432
realtime-db |  2023-09-05 16:38:00.069 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
realtime-db |  2023-09-05 16:38:00.077 UTC [29] LOG:  database system was shut down at 2023-09-05 16:25:23 UTC
realtime-server | Setting RLIMIT_NOFILE to 100000
realtime-db |  2023-09-05 16:38:00.083 UTC [1] LOG:  database system is ready to accept connections
realtime-db |  2023-09-05 16:38:00.084 UTC [35] LOG:  TimescaleDB background worker launcher connected to shared catalogs
realtime-db |  2023-09-05 16:38:00.085 UTC [37] LOG:  pg_cron scheduler started
realtime-server | 16:38:00.673 [error] Postgrex.Protocol (#PID<0.137.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (host.docker.internal:5432): non-existing domain - :nxdomain
realtime-server | 16:38:00.673 [error] Postgrex.Protocol (#PID<0.136.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (host.docker.internal:5432): non-existing domain - :nxdomain
realtime-server | 16:38:03.166 [error] Postgrex.Protocol (#PID<0.136.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (host.docker.internal:5432): non-existing domain - :nxdomain
realtime-server | 16:38:03.440 [error] Postgrex.Protocol (#PID<0.137.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (host.docker.internal:5432): non-existing domain - :nxdomain
realtime-server | 16:38:07.352 [error] Postgrex.Protocol (#PID<0.136.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (host.docker.internal:5432): non-existing domain - :nxdomain
realtime-server | 16:38:07.736 [error] Postgrex.Protocol (#PID<0.137.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (host.docker.internal:5432): non-existing domain - :nxdomain
realtime-server | 16:38:15.660 [error] Could not create schema migrations table. This error usually happens due to the following:
realtime-server | 
realtime-server |   * The database does not exist
realtime-server |   * The "schema_migrations" table, which Ecto uses for managing
realtime-server |     migrations, was defined by another library
realtime-server |   * There is a deadlock while migrating (such as using concurrent
realtime-server |     indexes with a migration_lock)
realtime-server | 
realtime-server | To fix the first issue, run "mix ecto.create".
realtime-server | 
realtime-server | To address the second, you can run "mix ecto.drop" followed by
realtime-server | "mix ecto.create". Alternatively you may configure Ecto to use
realtime-server | another table and/or repository for managing migrations:
realtime-server | 
realtime-server |     config :realtime, Realtime.Repo,
realtime-server |       migration_source: "some_other_table_for_schema_migrations",
realtime-server |       migration_repo: AnotherRepoForSchemaMigrations
realtime-server | 
realtime-server | The full error report is shown below.
realtime-server | 
realtime-server | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 14993ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
realtime-server | 
realtime-server |   1. Ensuring your database is available and that you can connect to it
realtime-server |   2. Tracking down slow queries and making sure they are running fast enough
realtime-server |   3. Increasing the pool_size (although this increases resource consumption)
realtime-server |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
realtime-server | 
realtime-server | See DBConnection.start_link/2 for more information
realtime-server | 
realtime-server |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
realtime-server |     (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
realtime-server |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1024: Ecto.Adapters.SQL.execute_ddl/4
realtime-server |     (ecto_sql 3.8.3) lib/ecto/migrator.ex:696: Ecto.Migrator.verbose_schema_migration/3
realtime-server |     (ecto_sql 3.8.3) lib/ecto/migrator.ex:510: Ecto.Migrator.lock_for_migrations/4
realtime-server |     (ecto_sql 3.8.3) lib/ecto/migrator.ex:422: Ecto.Migrator.run/4
realtime-server |     (ecto_sql 3.8.3) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
realtime-server |     nofile:1: (file)
realtime-server exited with code 1
```

## Expected behavior

A clean start.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by ventsyv** [comment]
Changing the DB image to supabase/postgres:15.1.0.103 and still getting the same error.

**Comment by ventsyv** [comment]
Adding 
```
 extra_hosts:      
  - "host.docker.internal:host-gateway"`
 ``` to the docker compose seems to have fixed the issue.

**Comment by filipecabaco** [comment]
Hi @ventsyv 

Thank you for reporting this. Going to check this issue as a priority.

Can you give me more details on what's your system information, mainly around your operating system and docker setup.

**Comment by TerminalFi** [comment]
Happening to me as well. Preventing me from using `supabase cli` to run realtime
@filipecabaco 

MacOS 14.1 (23B73)
Chip: Apple M1 Max

```yaml
Client:
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           orbstack

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:30 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.6
  GitCommit:        091922f03c2762540fd057fba91260237ff86acb
 runc:
  Version:          1.1.9
  GitCommit:        82f18fe0e44a59034f3e1f45e475fa5636e539aa
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ````

**Comment by TerminalFi** [comment]
Or rather maybe a different issue

```
realtime-server  | Setting RLIMIT_NOFILE to 100000
realtime-db      | ************* 2023-10-22 22:27:29.389 UTC [40] postgres@postgres ERROR:  no schema has been selected to create in at character 28
realtime-db      | ************* 2023-10-22 22:27:29.389 UTC [40] postgres@postgres STATEMENT:  CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" bigint, "inserted_at" timestamp(0), PRIMARY KEY ("version"))
realtime-server  | 22:27:29.396 [error] Could not create schema migrations table. This error usually happens due to the following:
realtime-server  |
realtime-server  |   * The database does not exist
realtime-server  |   * The "schema_migrations" table, which Ecto uses for managing
realtime-server  |     migrations, was defined by another library
realtime-server  |   * There is a deadlock while migrating (such as using concurrent
realtime-server  |     indexes with a migration_lock)
realtime-server  |
realtime-server  | To fix the first issue, run "mix ecto.create".
realtime-server  |
realtime-server  | To address the second, you can run "mix ecto.drop" followed by
realtime-server  | "mix ecto.create". Alternatively you may configure Ecto to use
realtime-server  | another table and/or repository for managing migrations:
realtime-server  |
realtime-server  |     config :realtime, Realtime.Repo,
realtime-server  |       migration_source: "some_other_table_for_schema_migrations",
realtime-server  |       migration_repo: AnotherRepoForSchemaMigrations
realtime-server  |
realtime-server  | The full error report is shown below.
realtime-server  |
realtime-server  | ** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) no schema has been selected to create in
realtime-server  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
```

**Comment by filipecabaco** [comment]
@TerminalFi and @ventsyv thank you for the feedback! Will check but indeed it's either something on the network or how we're starting up the containers 🤔

**Comment by filipecabaco** [comment]
@mrkpatchaa I think that might have a different origin but will also check 

@mrkpatchaa @TerminalFi @ventsyv do you remember how many cores you have allocated to your docker machine?

**Comment by TerminalFi** [comment]
10 CPUS / Cores

**Comment by ventsyv** [comment]
10 cores for me as well

**Comment by mrkpatchaa** [comment]
@filipecabaco any news? Thanks.

**Comment by filipecabaco** [comment]
Not yet sorry will pick this back up during the week

**Comment by Shusanta** [comment]
+1

**Comment by androoo** [comment]
I am also experiencing the same issue

**Comment by filipecabaco** [comment]
I wasn't able to replicate but I do have a couple of actions to see if we can fix this issue or at least make it move forward.

First of all I've opened two PRs to bump the version of Realtime to the latest version in production:
https://github.com/supabase/cli/pull/1653
https://github.com/supabase/supabase/pull/18874

Second, that SSL error could be related with the fact that we've added a SSL verification that is true by default and there might be old data / tenants that can be hitting this wall

To fix this: 
1. Connect to the database with psql: 
```bash
psql postgresql://supabase_admin:your-super-secret-and-long-postgres-password@127.0.0.1:5432/postgres
```
Do check your psql port using `docker ps` and check the password your .env file for the password. I'm using the default values from `.env.example` from `supabase/docker`. In CLI the password would be `postgres`

2. Run the following command to update all tenants with the `ssl_enforced` key to false
```sql
set search_path=_realtime;
UPDATE extensions SET settings = settings::jsonb || '{"ssl_enforced": false}'::jsonb;
```

Will keep trying replicating the issues found but do warn if this fixes part of the issues.

**Comment by mrkpatchaa** [comment]
I tried the ssl_enforced false and I don't see ssl error anymore. Now I get this error : `permission denied for schema realtime`

Full log : 

```
  | 11:56:59.498 project=my-realtime-dev external_id=my-realtime-dev [info] Applying migrations to db
  | 11:56:59.556 project=my-realtime-dev external_id=my-realtime-dev [error] Could not create schema migrations table. This error usually happens due to the following:
  | 
  |   * The database does not exist
  |   * The "schema_migrations" table, which Ecto uses for managing
  |     migrations, was defined by another library
  |   * There is a deadlock while migrating (such as using concurrent
  |     indexes with a migration_lock)
  | 
  | To fix the first issue, run "mix ecto.create".
  | 
  | To address the second, you can run "mix ecto.drop" followed by
  | "mix ecto.create". Alternatively you may configure Ecto to use
  | another table and/or repository for managing migrations:
  | 
  |     config :realtime, Realtime.Repo,
  |       migration_source: "some_other_table_for_schema_migrations",
  |       migration_repo: AnotherRepoForSchemaMigrations
  | 
  | The full error report is shown below.
  | 
  | 11:56:59.557 project=my-realtime-dev external_id=my-realtime-dev [error] Error starting Postgres Extention: {:error,
  |  {:shutdown,
  |   {:failed_to_start_child, Realtime.Tenants.Migrations,
  |    {%Postgrex.Error{
  |       message: nil,
  |       postgres: %{
  |         code: :insufficient_privilege,
  |         file: "aclchk.c",
  |         line: "3650",
  |         message: "permission denied for schema realtime",
  |         pg_code: "42501",
  |         position: "28",
  |         routine: "aclcheck_error",
  |         severity: "ERROR",
  |         unknown: "ERROR"
  |       },
  |       connection_id: 805602,
  |       query: nil
  |     },
  |     [
  |       {Ecto.Adapters.SQL, :raise_sql_call_error, 1,
  |        [
  |          file: 'lib/ecto/adapters/sql.ex',
  |          line: 932,
  |          error_info: %{module: Exception}
  |        ]},
  |       {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1658]},
  |       {Ecto.Adapters.SQL, :execute_ddl, 4,
  |        [file: 'lib/ecto/adapters/sql.ex', line: 1024]},
  |       {Ecto.Migrator, :verbose_schema_migration, 3,
  |        [file: 'lib/ecto/migrator.ex', line: 696]},
  |       {Ecto.Migrator, :lock_for_migrations, 4,
  |        [file: 'lib/ecto/migrator.ex', line: 510]},
  |       {Ecto.Migrator, :run, 4, [file: 'lib/ecto/migrator.ex', line: 422]},
  |       {Realtime.Repo, :with_dynamic_repo, 2,
  |        [file: 'lib/realtime/repo.ex', line: 12]},
  |       {Realtime.Tenants.Migrations, :init, 1,
  |        [file: 'lib/realtime/tenants/migrations.ex', line: 90]}
  |     ]}}}}
  | 11:56:59.603 [debug] Starting postgres stream extension with args: %{
  |   "db_host" => "QhixI0o7PYIABziLUL4f0A==",
  |   "db_name" => "sWBpZNdjggEPTQVlI52Zfw==",
  |   "db_password" => "***",
  |   "db_port" => "q2aah2pqWLpnzDBF7AhfLQ==",
  |   "db_socket_opts" => [:inet],
  |   "db_user" => "sWBpZNdjggEPTQVlI52Zfw==",
  |   "id" => "my-realtime-dev",
  |   "ip_version" => 4,
  |   "poll_interval_ms" => 100,
  |   "poll_max_changes" => 100,
  |   "poll_max_record_bytes" => 1048576,
  |   "publication" => "supabase_realtime",
  |   "region" => "us-west-1",
  |   "slot_name" => "supabase_realtime_replication_slot",
  |   "ssl_enforced" => false,
  |   "subs_pool_size" => 5
  | }
  | 11:56:59.605 project=my-realtime-dev external_id=my-realtime-dev [info] Applying migrations to db
^Ccanceled
```

**Comment by mrkpatchaa** [comment]
I am using self hosted and I tried a fresh database install by removing my volumes/db/data folder and restarting everything.

**Comment by mrkpatchaa** [comment]
Hmm I don't know what I did but it's working now.... I'll try again to recreate everything from scratch and let you know what fixed the issue.
Thanks.

**Comment by filipecabaco** [comment]
That error seems to be related with the credentials used to access the tenant database so probably there was something not properly setup.

Cleaning all the state makes it work because it refreshed the state fully hence being tricky to replicate

I also hope that the newer version makes things more stable so I hope to get those merged soon

**Comment by filipecabaco** [comment]
Ok just saw that at least CLI was merged 😁

**Comment by mrkpatchaa** [comment]
When creating the tenant, I needed to change db_user to supabase_admin to make it work.
```
curl -X POST \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer ****' \
  -d $'{
    "tenant" : {
      "name": "realtime-dev",
      "external_id": "realtime-dev",
      "jwt_secret": "****",
      "extensions": [
        {
          "type": "postgres_cdc_rls",
          "settings": {
            "db_name": "postgres",
            "db_host": "db",
            "db_user": "supabase_admin", <-- From my analysis this fixed my new issue.
            "db_password": "****",
            "db_port": "****",
            "region": "us-west-1",
            "poll_interval_ms": 100,
            "poll_max_record_bytes": 1048576,
            "ip_version": 4,
            "ssl_enforced": false <-- And of course this from Filipe
          }
        }
      ]
    }
  }' \
  http://localhost:4001/api/tenants
```
Now I am going to try on another env, where I cannot start from scratch 👀

**Comment by ventsyv** [comment]
In my case I was installing in my own database that doesn't have
supabase_admin and instead the admin user will I set up (called posters).

Is I possible that the supabade_admin user name is hardcoded somewhere? Or
that some env variable needs to be set??

**Comment by mrkpatchaa** [comment]
My case is self hosted to supabase_admin is used in the container env config.
```
   environment:
      PORT: 4000
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: supabase_admin
      DB_PASSWORD: ${POSTGRES_PASSWORD}
```
I closed #713 because it's fixed now.
