### ISSUE TITLE
Running realtime in a cluster - Postgres changes not working reliably 

### ISSUE THREAD

**Issue by colin-chadwick** [supabase/realtime#811]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When running in a cluster on AWS (using the Supabase on AWS community template), realtime is unable to broadcast most Postgres changes. It sometimes works, but is really unreliable. All other realtime events, for e. g. presence states or cursor positions work as expected. The DNS_NODES option is set.

## Expected behavior

Listening to Postgres changes should work reliably without any issues or interruptions.

## Screenshots

These logs are shown in the realtime logs when trying to watch Postgres changes in the cluster:
![Bildschirmfoto 2024-03-19 um 18 11 23](https://github.com/supabase/realtime/assets/62803839/4e8b1c77-27c5-47f2-a5cb-e1b4b13cc87a)

What is this "Error polling replication" all about?

**Comment by colin-chadwick** [comment]
It looks like the Supabase on AWS template isn't compatible with newer versions of Realtime. I was able to get this to work by setting the `ERL_AFLAGS` environment variable from `-proto_dist inet_tcp` to `-proto_dist inet6_tcp`. The `DNS_NODES` variable is important as well.  Here's the entire configuration: 
```yaml
environment: {
          PORT: '4000',
          DB_HOST: db.cluster.clusterEndpoint.hostname,
          DB_PORT: db.cluster.clusterEndpoint.port.toString(),
          DB_AFTER_CONNECT_QUERY: 'SET search_path TO realtime',
          DB_ENC_KEY: 'supabaserealtime',
          FLY_ALLOC_ID: 'fly123',
          FLY_APP_NAME: `realtime`,
          ERL_AFLAGS: '-proto_dist inet6_tcp',
          ENABLE_TAILSCALE: 'false',
          DNS_NODES: `realtime-dev.${namespaceName}`,
        },
secrets: {
          DB_USER: ecs.Secret.fromSecretsManager(
            supabaseAdminSecret,
            'username',
          ),
          DB_PASSWORD: ecs.Secret.fromSecretsManager(
            supabaseAdminSecret,
            'password',
          ),
          DB_NAME: ecs.Secret.fromSecretsManager(supabaseAdminSecret, 'dbname'),
          API_JWT_SECRET: ecs.Secret.fromSecretsManager(jwtSecret),
          SECRET_KEY_BASE: ecs.Secret.fromSecretsManager(cookieSigningSecret),
}
```
